// frameworks/svelte/src/scenarios/basic-chart-component.svelte
<script lang="ts">
    import { onMount } from 'svelte'
    import { Themes, lightningChart } from '@lightningchart/lcjs'
    import { type Scenario, } from 'shared';

    let chartRef: HTMLDivElement;
    let { activeScenario, theme }: { activeScenario: Scenario, theme: keyof typeof Themes } = $props();

    onMount(() => {
        if (!chartRef) return;
        const lc = lightningChart({ license: import.meta.env.VITE_LCJS_LICENSE, });
        const chart = lc.ChartXY({ 
            container: chartRef, 
            theme: Themes[theme],
        })
            .setTitle(`Svelte: ${activeScenario.label}`);
        const points= [];
        for (let i = 0; i < 20; i++) {
            points.push({
                x: i,
                y: i
            })
        }
        chart.addPointSeries({
            schema: {
                x: { pattern: 'progressive' },
                y: { pattern: 'progressive' }
            }
        })
            .appendJSON(points);

        return () => {
            chart.dispose();
            lc.dispose();
        }
    })
</script>

<div bind:this={chartRef} style="width: 100%; height: 100%;"></div>

// frameworks/vue/src/scenarios/basic-chart-component.vue
<template>
	<div ref="chartRef" style="width: 100%; height: 100%;" />
</template>

<script lang="ts">
import { ref, shallowRef, onMounted, PropType, onBeforeUnmount, onErrorCaptured } from 'vue'
import { lightningChart, Themes } from "@lightningchart/lcjs";
import { Scenario } from "shared";

export default {
	name: "BasicChartComponent",
	props: {
		activeScenario: { type: Object as PropType<Scenario>, required: true },
		theme: { type: Object as PropType<keyof typeof Themes>, required: true }
	},
	setup(props) {
		const chartRef = ref<HTMLDivElement | null>(null);
		const lc = shallowRef();
		const chart = shallowRef();

		const createChart = () => {
			lc.value = lightningChart({ license: import.meta.env.VITE_LCJS_LICENSE, });
			chart.value = lc.value.ChartXY({
				container: chartRef.value,
				theme: Themes[props.theme],
			});
			if (!chartRef.value || !chart.value || !props.activeScenario) return;
			chart.value.setTitle(`Vue: ${props.activeScenario.label}`);
		}
		const setupData = () => {
			if (!chart.value || !props.activeScenario) return;
			const points= []
			for (let i = 0; i < 20; i++) {
				points.push({
					x: i,
					y: i
				})
			}
			chart.value.addPointSeries({
				schema: {
					x: { pattern: 'progressive' },
					y: { pattern: null }
				}
			})
				.appendJSON(points);
		}
		onMounted(() => {
			createChart();		
			setupData();
		})
		onBeforeUnmount(() => {
			if (lc.value) lc.value.dispose();
		})
		onErrorCaptured((err, _vm, info) => {
			console.error(`Error captured in component: ${info}`, err);
		})
		return {
			chartRef,
		};
	}
};
</script>
