// frameworks/svelte/src/scenarios/basic-chart-component.svelte
<script lang="ts">
    import { onMount } from 'svelte'
    import { Themes, lightningChart } from '@lightningchart/lcjs'
    import { type Scenario, } from 'shared';

    let chartRef: HTMLDivElement;
    let { activeScenario, theme }: { activeScenario: Scenario, theme: keyof typeof Themes } = $props();

    onMount(() => {
        if (!chartRef) return;
        const lc = lightningChart({ license: import.meta.env.VITE_LCJS_LICENSE, });
        const chart = lc.ChartXY({ 
            container: chartRef, 
            theme: Themes[theme],
        })
            .setTitle(`Svelte: ${activeScenario.label}`);
        const points= [];
        for (let i = 0; i < 20; i++) {
            points.push({
                x: i,
                y: i
            })
        }
        chart.addPointSeries({
            schema: {
                x: { pattern: 'progressive' },
                y: { pattern: 'progressive' }
            }
        })
            .appendJSON(points);

        return () => {
            chart.dispose();
            lc.dispose();
        }
    })
</script>

<div bind:this={chartRef} style="width: 100%; height: 100%;"></div>

// frameworks/angular/src/scenarios/basic-chart-component.ts
import { afterNextRender, Component, ElementRef, Input, OnDestroy, ViewChild } from '@angular/core';
import { Themes } from "@lightningchart/lcjs";
import { LcContextService } from '../lc-context/lc-context.service';
import { Scenario } from "shared";

@Component({
	selector: 'basic-chart-component',
	template: `<div #chartRef style="width: 100%; height: 100%;"></div>`,
})
export class BasicChartComponent implements OnDestroy {
    @ViewChild('chartRef', { static: false }) chartRef!: ElementRef<HTMLDivElement>;
    @Input({ required: true }) theme!: keyof typeof Themes; 
    @Input({ required: true }) activeScenario!: Scenario;
    private destroyLC?: () => void;
    
    constructor(lcContextService: LcContextService) {
    	afterNextRender(() => {
    		const lc = lcContextService.getLightningChartContext();
    		const container = this.chartRef.nativeElement;
    		const chart = lc.ChartXY({ 
    			container, 
    			theme: Themes[this.theme], 
    		})			
    			.setTitle(`Angular: ${this.activeScenario.label}`);
                
    		const points= [];
    		for (let i = 0; i < 20; i++) {
    			points.push({
    				x: i,
    				y: i
    			})
    		}
    		chart.addPointSeries({
    			schema: {
    				x: { pattern: 'progressive' },
    				y: { pattern: 'progressive' }
    			}
    		})
    			.appendJSON(points);

    		this.destroyLC = () => {
    			chart.dispose();
    		}
    	})
    };
    
    ngOnDestroy(): void {
    	if (this.destroyLC) {
    		this.destroyLC(); 
    	} 
    };
}
